services:
  app:
    build:
      context: .
      dockerfile: docker/archive.Dockerfile
      args:
        DATABASE_URL: "postgresql://postgres:postgres@nfmw_postgres:5432/appdb"
    container_name: nfmw_archive
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@nfmw_postgres:5432/appdb"
    ports:
      - "8074:8074"
    volumes:
      - nfmw_archive:/archive
    command: cargo run --release

  db:
    image: postgres:18
    container_name: nfmw_postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "appdb"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - nfmw_pgdata:/var/lib/postgresql

volumes:
  nfmw_pgdata:
  nfmw_archive:
